FROM python:3.12-slim

WORKDIR /app

ENV PYTHONPATH=/app

# Install curl (optional, but good for debugging)
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["celery", "-A", "worker.celery_app", "worker", "--loglevel=info"]
