all:
  children:
    swarm_managers:
      hosts:
        homelab-vm:
          ansible_host: 192.168.122.166
          ansible_user: gyinae
          # ansible_password: your_password (use --ask-pass)
